#spring.application.name=mini-cti

# Database settings
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:minicti}
spring.datasource.username=${DB_USER:cf9}
spring.datasource.password=${DB_PASS:Coding571!}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


app.security.secret-key=6Vfq2QzhPn0FP1Dnl1R+cRSWMndd4jqDEiv4p9v1oHAUSOfjtHqz7eAtDwinvHlO
app.security.jwt-expiration=10800000

#Virus total API KEY
app.virustotal.api.key=${VIRUSTOTAL_API_KEY}

# make sure to use JOIN FETCH
spring.jpa.open-in-view=false


